---

- name: Install apt packages
  ansible.builtin.apt:
    pkg: {{ apt_packages }}

- name: Install pip packages
  ansible.builtin.pip:
    name: {{ python_packages }}

- name: Make tools directory
  ansible.builtin.file:
    path: ~/tools/
    state: directory
    mode: '0755'

- name: Download git packages
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: ~/tools/
  loop: {{ git_packages }}
